import type { Metadata } from "next";
import { Geist, Figtree, IBM_Plex_Mono, Sora } from "next/font/google";
import "./globals.css";
import GridColumns from "@/components/providers/grid-provider";
import GSAPProvider from "@/components/providers/gsap-provider";
import GetInTouch from "@/components/get-in-touch";
import { TooltipProvider } from "@/components/ui/tooltip";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["400", "500", "600"],
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={figtree.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${ibmPlexMono.variable} ${sora.variable} antialiased`}
      >
        {/*<div className="bg"></div>*/}
        <GSAPProvider>
          <TooltipProvider>{children}</TooltipProvider>
          {/*<Footer />*/}
        </GSAPProvider>
      </body>
    </html>
  );
}
